grpc:
  server:
    port: 3005
  client:
    action:
      address: 'static://127.0.0.1:3003'
      negotiation-type: plaintext
    im:
      address: 'static://127.0.0.1:3004'
      negotiation-type: plaintext
    recommend:
      address: 'static://127.0.0.1:3006'
      negotiation-type: plaintext
spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/violet?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  elasticsearch:
    uris: localhost:9200
  data:
    mongodb:
      host: localhost
      port: 27017
      database: violet
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer