server:
  port: 3002
grpc:
  server:
    port: 3012
  client:
    demo:
      address: 'static://127.0.0.1:3011'
      negotiation-type: plaintext
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/violet?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  elasticsearch:
    uris: localhost:9200